language: java

jdk: oraclejdk7

before_install:
  - export TERM=dumb
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
  - export COMPONENTS=build-tools-19.1.0,android-19,extra-android-support,extra-android-m2repository,extra-google-m2repository
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env
  - ./tmp-update-gradle-android-test-plugin.sh
  - ./tmp-update-robospock-plugin.sh

notifications:
  email: true
